wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1642948123
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      3:
      - 1
      4: 3.7.12
      5: 0.12.9
      8:
      - 5
    visualize:
      Conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      PR_test:
        panel_config:
          fieldSettings:
            class: class
            x: recall
            y: precision
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: Precision v. Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: PR_test_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      ROC_test:
        panel_config:
          fieldSettings:
            class: class
            x: fpr
            y: tpr
          panelDefId: wandb/area-under-curve/v0
          stringSettings:
            title: ROC
            x-axis-title: False positive rate
            y-axis-title: True positive rate
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: ROC_test_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
